name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 2.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish WordCounterApp/WordCounterApp.csproj -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: WordCounterApp\bin\Release\netcoreapp2.1\win10-x64\publish\
