name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
    - uses: actions/cache@v3
      with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
        ${{ runner.os }}-nuget-
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger "trx" --results-directory "./TestResults"
    - uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
      
    - name: Publish
      run: dotnet publish WordCounterApp/WordCounterApp.csproj -c Release
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: publish
        path: WordCounterApp/bin/Release/net6.0/publish/
